### PR TITLE
feat: supports multiple compose files

### PR DESCRIPTION
**Pull request by neilime**
### `compose-file`

Can be a list of files:

```yml
compose-file: |
  docker-compose.yml
  docker-compose.ci.yml
```

### CODE REVIEW

**Comment by isbang** [comment]
Thank you for your contribution! May I ask when this function is needed? And please fix ci test.

**Comment by neilime** [comment]
> Thank you for your contribution! May I ask when this feature is needed? And please fix ci test.

It is common to manage several docker-compose files depending the context of usage: 

- docker-compose.base.yml: describe services and common settings
- docker-compose.dev.yml: add extra configuration for development purpose
- docker-compose.ci.yml: add extra configuration for CI purpose

So for running services in CI mode, we need to run `docker-compose up -f docker-compose.base.yml -f docker-compose.ci.yml up`

**Review by isbang — APPROVED** [review]
LGTM

Do you want to merge your self?

**Comment by neilime** [comment]
> LGTM
> 
> Do you want to merge your self?

I cannot merge, I let you do it

**Pull request merged**
